@startuml

title __CASSETETE's Class Diagram__\n

  namespace CasseTete {
    class CasseTete.Model {
        {static} - BOARDSIZE_X : int
        {static} - BOARDSIZE_Y : int
        {static} - NBRPAIRSYMBOL : int
        {static} - NBRSYMBOL : int
        - board : Cell[][]
        - boardTemp : Cell[][]
        - pathList : ArrayList<Cell>
        - pathListTemp : ArrayList<Cell>
        + GenerateBoard()
        + Model()
        + OnClickUndo()
        + getBoard()
        + parcoursDD()
        + startDD()
        + stopDD()
        - AcceptedJump()
        - CellInsidePathList()
        - CellSymbolInsidePathListTemp()
        - CreateEmptyBoard()
        - GeneratePath()
        - GenerateRandomSymbol()
        - ModifyPreviousCell()
        - checkSymbol()
        - deleteCellPath()
        - hasWon()
        - isEmpty()
        - removeCellPath()
        - resetCellPath()
    }
  }
  

  namespace CasseTete {
    class CasseTete.PathCoordinate {
        - x : int
        - y : int
        + PathCoordinate()
        + getX()
        + getY()
        + setX()
        + setY()
    }
  }
  

  namespace CasseTete {
    class CasseTete.View {
        - x : int
        - y : int
        + View()
        + start()
        - CellPathToImg()
        - ControllerOnClickNewGame()
        - ControllerOnClickUndo()
        - ControllerOnDragDetected()
        - ControllerOnDragDone()
        - ControllerOnDragEntered()
        - setDDOnImageView()
        - victoryPopup()
    }
  }
  

  CasseTete.Model -up-|> java.util.Observable
  CasseTete.View -up-|> javafx.application.Application
  CasseTete.View o-- CasseTete.Model : model


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
