@startuml

title __CASSETETE's Class Diagram__\n

  namespace CasseTete {
    abstract class CasseTete.Cell {
        - occupied : boolean
        - x : int
        - y : int
        + Cell()
        + getX()
        + getY()
        + isOccupied()
        + setOccupied()
        + setX()
        + setY()
    }
  }
  

  namespace CasseTete {
    class CasseTete.CellEmpty {
        + CellEmpty()
    }
  }
  

  namespace CasseTete {
    class CasseTete.CellPath {
        + CellPath()
    }
  }
  

  namespace CasseTete {
    class CasseTete.CellSymbol {
        - symbole : Text
        + CellSymbol()
        + getSymbole()
        + setSymbole()
    }
  }
  

  namespace CasseTete {
    class CasseTete.Controller {
        + Controller()
        + ControllerOnDragDetected()
        + ControllerOnDragDone()
        + ControllerOnDragEntered()
    }
  }
  

  namespace CasseTete {
    class CasseTete.Model {
        - lastC : int
        - lastR : int
        - textO : Text
        - textX : Text
        + GenerateBoard()
        + parcoursDD()
        + startDD()
        + stopDD()
        - CreateEmptyBoard()
        - GenerateRandomSymbol()
    }
  }
  

  namespace CasseTete {
    class CasseTete.View {
        + View()
        + start()
    }
  }
  

  CasseTete.CellEmpty -up-|> CasseTete.Cell
  CasseTete.CellPath -up-|> CasseTete.Cell
  CasseTete.CellSymbol -up-|> CasseTete.Cell
  CasseTete.Model -up-|> java.util.Observable
  CasseTete.View -up-|> javafx.application.Application
  CasseTete.View o-- CasseTete.Controller : controller
  CasseTete.View o-- CasseTete.Model : model


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
